name: Deploy FastAPI to Amazon Lightsail

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Build, tag, and push FastAPI image to Amazon ECR Public
      id: build-fastapi-image
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: d0v2k3o3
        REPOSITORY: ohmyservice_backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --no-cache -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        echo "backend_image=$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Install SSH client and sshpass
      run: sudo apt-get install -y openssh-client sshpass

    - name: Ensure .env directory exists on Lightsail instance
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP "mkdir -p /home/$SSH_USERNAME"

    - name: Copy .env file to Lightsail instance
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no .env $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP:/home/$SSH_USERNAME/.env

    - name: Deploy to Amazon Lightsail
      env:
        BACKEND_IMAGE: ${{ steps.build-fastapi-image.outputs.backend_image }}
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP << EOF
          set -e
          BACKEND_IMAGE=${BACKEND_IMAGE}

          # Pull the latest image
          sudo docker pull \\$BACKEND_IMAGE

          # Stop and remove existing containers
          sudo docker stop fastapi_app || true
          sudo docker rm fastapi_app || true

          # Run the new container with Uvicorn's recommended settings
          sudo docker run -d --name fastapi_app \
            --env-file /home/$SSH_USERNAME/.env \
            -p 28282:8000 \
            --restart unless-stopped \
            \\$BACKEND_IMAGE \
            uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --lifespan on

          # Output logs for debugging
          sleep 5
          sudo docker logs fastapi_app || true
        EOF
